# Generated by Django 5.0.6 on 2024-05-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fam', '0002_rename_imagen_familymemb_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymemb',
            name='price',
            field=models.IntegerField(verbose_name='Price'),
        ),
    ]
