# Generated by Django 5.2.1 on 2025-05-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fam', '0003_alter_familymemb_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('image', models.ImageField(null=True, upload_to='images/', verbose_name='Image')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('stock', models.IntegerField(null=True, verbose_name='Stock')),
            ],
        ),
        migrations.DeleteModel(
            name='familymemb',
        ),
    ]
